### ISSUE TITLE
Feature Suggestion: X/Y offset

### ISSUE THREAD

**Issue by 8PercentAndroid** [MiSTer-devel/AtariLynx_MiSTer#1]
Excellent core already in its current state.
Request is as follows:
Provide a save-able option to move the picture in x and y directions for CRT output.
This is currently available in other cores and helps with the variance that you can experience across different CRTs 

Thanks

**Comment by RobertPeip** [comment]
I can do this for 240p mode. Please let us define what range it should have. 
E.g.: +-7 in steps of 1 for both x/y

**Comment by RobertPeip** [comment]
done

**Comment by 8PercentAndroid** [comment]
Excellent, thanks Robert!
