### ISSUE TITLE
(scanline) timing too tight

### ISSUE THREAD

**Issue by enthusi** [MiSTer-devel/AtariLynx_MiSTer#11]
The current core glitches (heavily) in the title picture of available homebrew game assembloids:
https://atarigamer.com/lynx/game/Assembloids/8913075
That part changes the palette every screen line. Works on real hardware, mednafen (albeit mednafen's timing is known to be crude) and reportedly also on mister when 'cpu+gpu turbo' are enabled.
The code to write the palette is a plain selfmodified unrolled loop of 
```
label00=*+1
    lda #00
    sta $fda4
    lda #00
    sta $fdb4
...
   lda luchs_pal+0*102,y
   sta label00
...
```

**Comment by RobertPeip** [comment]
Thanks for the bug entry. 

Fixed with the new release.
