### ISSUE TITLE
Feature suggestion: add Scale options (as in GB, GBC, GBA cores)

### ISSUE THREAD

**Issue by eturquin** [MiSTer-devel/AtariLynx_MiSTer#2]
Super useful to force integer scaling (while not having to force it on all cores).

**Comment by RobertPeip** [comment]
Maybe i'm missing something, but you can force scale to integer with the MiSTer.ini

[AtariLynx]
vscale_mode=1

**Comment by SegaSnatcher** [comment]
I think he's talking about the Scale H/V options in those other cores. 

Using GBA as an example.

https://github.com/MiSTer-devel/GBA_MiSTer/commit/e40f3a291e6d40f7de2baa10fe8360ebbdca924a

**Comment by eturquin** [comment]
> I think he's talking about the Scale H/V options in those other cores.
> 
> Using GBA as an example.
> 
> [MiSTer-devel/GBA_MiSTer@e40f3a2](https://github.com/MiSTer-devel/GBA_MiSTer/commit/e40f3a291e6d40f7de2baa10fe8360ebbdca924a)

Yes, that's what I had in mind indeed. In the meantime I'll go with Robert's suggestion, thanks!

**Comment by RobertPeip** [comment]
H/V scaling is now implemented
