### ISSUE TITLE
Feature Request: Flip Screen Option as a Mappable Input Button

### ISSUE THREAD

**Issue by KremlingKuthroat19** [MiSTer-devel/AtariLynx_MiSTer#4]
This core is absolutely fantastic! You've done a wonderful job Mr. FPGAzumSpass! I'm really enjoying the Atari Lynx games :)

One feature that'd make this core perfect for me is if the screen flip option can be mapped to a controller button for the toggle. There are 3 screen orientations, so just being able to have a "Screen Flip" button as an extra button to be able to flip the screen between all 3 orientations would be outstanding.

**Comment by RobertPeip** [comment]
The Lynx usually has a screen flip button combination build in.
I will try to get that working.

**Comment by RobertPeip** [comment]
Support of Lynx built in Flip mode(option2+pause) is done
