### ISSUE TITLE
Speed is seems slightly off

### ISSUE THREAD

**Issue by bstar** [MiSTer-devel/AtariLynx_MiSTer#6]
All of the games I've played feel a bit too fast (cpu turbo off).  Lemmings and Gates of Zendocon were very obvious to me.

**Comment by RobertPeip** [comment]
I have a Lynx 2 with Gates of Zendocon here and they match pretty good.
Unfortunatly i cannot create a good video of it that captures both screen, this one is the best I could do:
https://www.youtube.com/watch?v=KgEsvRoyVMs

At least you can see that the explosion happens at the same time after ~20 seconds of gameplay.

What are you comparing to?

**Comment by bstar** [comment]
I will do a slow motion video this weekend (need to put my lynx back together) and see if I can compare frames.  At the moment I'm going off of 30 years of muscle memory, it just feels slightly off.  I'll see if I can do a slow motion comparison and see how many frames off it is (if any).  The Lemmings scaling effect seems too fast and the Gates of Zendocon ship acceleration seems too fast as well.  On the other hand, California Games feels perfect.  I'll confirm with some evidence asap.  It goes without saying, wonderful work Robert.

**Comment by RobertPeip** [comment]
It's been a month now. Any news on this one? 
Otherwise i will close this.
