### ISSUE TITLE
Feature Request: Cheat Engine support

### ISSUE THREAD

**Issue by KremlingKuthroat19** [MiSTer-devel/AtariLynx_MiSTer#8]
Robert. Your core is amazing! Thanks so much and I'm excited to see the WonderSwan in the future :).

I just wanted to do a feature request for adding cheat support. There are 18 Lynx games that have cheats: https://gamehacking.org/system/lnx/all.

Can you please add cheat support for the Lynx core?

**Comment by RobertPeip** [comment]
There is currently no MiSTer format available for Lynx Cheats.

Will ask rimsky82 if he can provide it.
If it's available, I can implement it.

**Comment by RobertPeip** [comment]
done
