### ISSUE TITLE
Controls are improperly labelled / mapped

### ISSUE THREAD

**Issue by Left-Empty** [MiSTer-devel/AtariLynx_MiSTer#9]
Greetings,

In the last version (20210413) with the current main (20210504), control mapping of the directions is a bit of a mess. None of the mapped directions actually correspond to the real one. I had to tweak around to finally manage to get a proper up/down/left/right setup, but I'm not willing to try to map it again to tell you which is which.
I am unsure if I hadn't fired the core in a month, or if this behavior happened after updating main.

Cheers, amazing core!

**Comment by RobertPeip** [comment]
It works correct here. 

Did you try to map while in a 90° or 270° game or with rotated screen? Depending on the rotation option the keys are rotated, too, so they may not match in that condition.

**Comment by Left-Empty** [comment]
Oh, thank you for the reply.
I had the option set to vertical rotation 270 in the option, which I hadn't noticed and thought it was only an option for LCD displays (playing myself on CRT). I hadn't realized it was an option to actually mimick turning the console itself!
Sorry for the false issue and, again, thank you for this incredible core: I was introduced to this system's numerous gems, especially the only real version of Slimeworld, last year and it's a joy to play them so beautifully.
